// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ndreyserg/gophermart/internal/model"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, name, passHash string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, passHash)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, name, passHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, name, passHash)
}

// FindByLoginAndPassHash mocks base method.
func (m *MockUserRepository) FindByLoginAndPassHash(ctx context.Context, login, passHash string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLoginAndPassHash", ctx, login, passHash)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLoginAndPassHash indicates an expected call of FindByLoginAndPassHash.
func (mr *MockUserRepositoryMockRecorder) FindByLoginAndPassHash(ctx, login, passHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLoginAndPassHash", reflect.TypeOf((*MockUserRepository)(nil).FindByLoginAndPassHash), ctx, login, passHash)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, number string, userID int) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, number, userID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, number, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, number, userID)
}

// FindByNumber mocks base method.
func (m *MockOrderRepository) FindByNumber(ctx context.Context, number string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", ctx, number)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockOrderRepositoryMockRecorder) FindByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockOrderRepository)(nil).FindByNumber), ctx, number)
}

// GetByUserID mocks base method.
func (m *MockOrderRepository) GetByUserID(ctx context.Context, userID int) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockOrderRepository) Update(ctx context.Context, order *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrderRepositoryMockRecorder) Update(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrderRepository)(nil).Update), ctx, order)
}

// UpdateAndAccrue mocks base method.
func (m *MockOrderRepository) UpdateAndAccrue(ctx context.Context, order *model.Order, accountID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAndAccrue", ctx, order, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAndAccrue indicates an expected call of UpdateAndAccrue.
func (mr *MockOrderRepositoryMockRecorder) UpdateAndAccrue(ctx, order, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAndAccrue", reflect.TypeOf((*MockOrderRepository)(nil).UpdateAndAccrue), ctx, order, accountID)
}

// MockAccountReposity is a mock of AccountReposity interface.
type MockAccountReposity struct {
	ctrl     *gomock.Controller
	recorder *MockAccountReposityMockRecorder
}

// MockAccountReposityMockRecorder is the mock recorder for MockAccountReposity.
type MockAccountReposityMockRecorder struct {
	mock *MockAccountReposity
}

// NewMockAccountReposity creates a new mock instance.
func NewMockAccountReposity(ctrl *gomock.Controller) *MockAccountReposity {
	mock := &MockAccountReposity{ctrl: ctrl}
	mock.recorder = &MockAccountReposityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountReposity) EXPECT() *MockAccountReposityMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountReposity) Create(ctx context.Context, userID int) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountReposityMockRecorder) Create(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountReposity)(nil).Create), ctx, userID)
}

// FindByUserID mocks base method.
func (m *MockAccountReposity) FindByUserID(ctx context.Context, userID int) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockAccountReposityMockRecorder) FindByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockAccountReposity)(nil).FindByUserID), ctx, userID)
}

// GetWithdrawals mocks base method.
func (m *MockAccountReposity) GetWithdrawals(ctx context.Context, accID int) ([]*model.AccountWithdrawals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, accID)
	ret0, _ := ret[0].([]*model.AccountWithdrawals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockAccountReposityMockRecorder) GetWithdrawals(ctx, accID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockAccountReposity)(nil).GetWithdrawals), ctx, accID)
}

// GetWithdrawn mocks base method.
func (m *MockAccountReposity) GetWithdrawn(ctx context.Context, accID int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawn", ctx, accID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawn indicates an expected call of GetWithdrawn.
func (mr *MockAccountReposityMockRecorder) GetWithdrawn(ctx, accID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawn", reflect.TypeOf((*MockAccountReposity)(nil).GetWithdrawn), ctx, accID)
}

// Withdraw mocks base method.
func (m *MockAccountReposity) Withdraw(ctx context.Context, accountID int, sum float64, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, accountID, sum, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockAccountReposityMockRecorder) Withdraw(ctx, accountID, sum, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockAccountReposity)(nil).Withdraw), ctx, accountID, sum, orderNumber)
}

// MockAccrualReposity is a mock of AccrualReposity interface.
type MockAccrualReposity struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualReposityMockRecorder
}

// MockAccrualReposityMockRecorder is the mock recorder for MockAccrualReposity.
type MockAccrualReposityMockRecorder struct {
	mock *MockAccrualReposity
}

// NewMockAccrualReposity creates a new mock instance.
func NewMockAccrualReposity(ctrl *gomock.Controller) *MockAccrualReposity {
	mock := &MockAccrualReposity{ctrl: ctrl}
	mock.recorder = &MockAccrualReposityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualReposity) EXPECT() *MockAccrualReposityMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAccrualReposity) Get(orderNumber string) (*model.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orderNumber)
	ret0, _ := ret[0].(*model.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAccrualReposityMockRecorder) Get(orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccrualReposity)(nil).Get), orderNumber)
}
